export const Gov = {
  Ariana: [
    "Ariana Medina",
    "Ettadhamen",
    "Kalaat el Andalous",
    "Mnihla",
    "Raoued",
    "Sidi Thabet",
    "Soukra"
  ],
  Beja: [
    "Amdoun",
    "Bea Nord",
    "Beja Sud",
    "Goubellat",
    "Medjez El Bab",
    "Nefza",
    "Teboursouk",
    "Testour",
    "Tibar"
  ],
  "Ben Arous": [
    "Ben Arous",
    "Bou Mhel El Bassatine",
    "El Mourouj",
    "Ezzahra",
    "Fouchana",
    "Hammam Chatt",
    "Hammam Lif",
    "La Nouvelle Medina",
    "Megrine",
    "Mohamedia",
    "Mornag",
    "Rades"
  ],
  Bizerte: [
    "Bizerte Nord",
    "Bizerte Sud",
    "Djoumine",
    "El Alia",
    "Ghar El Melh",
    "Ghezala",
    "Mateur",
    "Menzel Bourguiba",
    "Menzel Jemil",
    "Ras Jabel",
    "Sejenane",
    "Tinja",
    "Utique",
    "Zarzouna"
  ],
  Gabes: [
    "El Hamma",
    "El Metouia",
    "Gabes Medina",
    "Gabes Ouest",
    "Gabes Sud",
    "Ghannouch",
    "Menzel El Habib",
    "Mareth",
    "Matmata",
    "Nouvelle Matmata"
  ],
  Gafsa: [
    "Belkhir",
    "El Guetar",
    "El Ksar",
    "Gafsa Nord",
    "Gafsa Sud",
    "Mdhilla",
    "Metlaoui",
    "Oum El Araies",
    "Redeyef",
    "Sidi AÃ¯ch",
    "Sned"
  ],
  Jendouba: [
    "Jendouba",
    "Bou Salem",
    "Tabarka",
    "AÃ¯n Draham",
    "Fernana",
    "Beni M'Tir",
    "Ghardimaou",
    "Oued Melliz"
  ],
  Kairouan: [
    "Kairouan",
    "Chebika",
    "Sbikha",
    "Oueslatia",
    "AÃ¯n Djeloula",
    "Haffouz",
    "AlaÃ¢",
    "Hajeb El Ayoun",
    "Nasrallah",
    "Menzel Mehiri",
    "Echrarda",
    "Bou Hajla"
  ],
  Kasserine: [
    "El Ayoun",
    "Ezzouhour",
    "FÃ©riana",
    "Foussana",
    "HaÃ¯dra",
    "Hassi El Ferid",
    "Jedelienne",
    "Kasserine Nord",
    "Kasserine Sud",
    "Majel Bel AbbÃ¨s",
    "SbeÃ¯tla",
    "Sbiba",
    "Thala"
  ],
  Gebili: ["Kebili", "Djemna", "Douz", "El GolÃ¢a", "Souk Lahad"],
  Kef: [
    "El Kef",
    "Nebeur",
    "Touiref",
    "Sakiet Sidi Youssef",
    "Tajerouine",
    "Menzel Salem",
    "Kalaat es Senam",
    "KalÃ¢at Khasba",
    "JÃ©rissa",
    "El Ksour",
    "Dahmani",
    "Sers"
  ],
  Mahdia: [
    "Mahdia",
    "Rejiche",
    "Bou Merdes",
    "Ouled Chamekh",
    "Chorbane",
    "Hebira",
    "Essouassi",
    "El Djem",
    "Kerker",
    "Chebba",
    "MelloulÃ¨che",
    "Sidi Alouane",
    "Ksour Essef",
    "El BradÃ¢a"
  ],
  Manouba: [
    "Borj El Amri",
    "Djedeida",
    "Douar Hicher",
    "El Battan",
    "Manouba",
    "Mornaguia",
    "Oued Ellil",
    "Tebourba"
  ],
  Medenine: [
    "Medenine",
    "Beni Khedache",
    "Ben Gardane",
    "Zarzis",
    "Houmt El Souk (Djerba)",
    "Midoun (Djerba)",
    "Ajim (Djerba)"
  ],
  Monastir: [
    "Monastir (capital)",
    "Amiret El Fhoul",
    "Amiret El Hojjaj",
    "Amiret Touazra",
    "Bekalta",
    "Bembla",
    "Beni Hassen",
    "Bennane",
    "Bouhjar",
    "Cherahil",
    "El MasdourGhenada",
    "Jemmal",
    "Zaouiet",
    "Kontoch",
    "Khniss",
    "Ksar Hellal",
    "Ksibet el-Mediouni",
    "Lamta",
    "Menzel Ennour",
    "Menzel Farsi",
    "Menzel Hayet",
    "Menzel Kamel",
    "Moknine",
    "Ouerdanin",
    "Sayada",
    "Teboulba",
    "Touza"
  ],
  Nabeul: [
    "BÃ©ni Khalled",
    "BÃ©ni Khiar",
    "Bou Argoub",
    "Dar ChÃ¢abane El Fehri",
    "El Haouaria",
    "El Mida",
    "Grombalia",
    "Hammam El Guezaz",
    "Hammamet",
    "KÃ©libia",
    "Korba",
    "Menzel Bouzelfa",
    "Menzel Temime",
    "Nabeul",
    "Soliman",
    "Takelsa"
  ],
  Sfax: [
    "Sfax",
    "Sakiet Ezzit",
    "Chihia",
    "Sakiet Eddaeer",
    "Gremda",
    "El Ain",
    "Thyna",
    "Agareb",
    "Jebiniana",
    "El Hencha",
    "Menzel Chaker",
    "GhraÃ¯ba",
    "Bir Ali Ben Khelifa",
    "Skhira",
    "Mahares",
    "Kerkennah"
  ],
  "Sidi Bouzid": [
    "Sidi Bouzid (capital)",
    "Bir El Hafey",
    "Cebbala Ouled Asker",
    "Jilma",
    "Menzel Bouzaiane",
    "Meknassy",
    "Mezzouna",
    "Ouled Haffouz",
    "Regueb",
    "Sidi Ali Ben Aoun"
  ],
  Siliana: [
    "Siliana",
    "Bou Arada",
    "GaÃ¢four",
    "El Krib",
    "Sidi Bou Rouis",
    "Maktar",
    "Rouhia",
    "Kesra",
    "Bargou",
    "El Aroussa"
  ],
  Sousse: [
    "Sousse Jaouhara",
    "Sousse Medina",
    "Sousse Riadh",
    "Sousse Sidi AbdelhamidAkouda",
    "Bouficha",
    "Enfidha",
    "Hammam Sousse",
    "Hergla",
    "Kalaa Kebira",
    "Kalaa Sghira",
    "Kondar",
    "M'Saken",
    "Sidi Bou Ali",
    "Sidi El Heni"
  ],
  Tataouine: ["Tataouine", "Bir Lahmar", "Ghomrassen", "Dehiba", "Remada"],
  Tozeur: ["Tozeur", "Degache", "Hamet Jerid", "Nafta", "Tamerza"],
  Tunis: [
    "Tunis",
    "Le Bardo",
    "Le Kram",
    "La Goulette",
    "Carthage",
    "Sidi Bou Said",
    "La Marsa",
    "Sidi Hassine"
  ],
  Zaghouan: [
    "Zaghouan",
    "Zriba",
    "Bir Mcherga",
    "Djebel Oust",
    "El Fahs",
    "Nadhour"
  ]
};
